blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    # path('', blog, name='blog'),
    path('post-list/', post_list, name='post_list'),
    # path('', post_detail, name='post-detail'),
]

client/urls.py
from django.urls import path
from .views import *

app_name = "client"

urlpatterns = [
    path('', dashboard, name='index'),
    path('sms/', sendsms, name='sms'),
    # path('signing/', signing, name='login'),
    # path('logout', logout, name='logout'),
]

firstacademy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('client.urls')),
    path('blog/', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
from PIL import Image
from datetime import datetime
from slugify import slugify
User = get_user_model()

# Create your models here.
def post_image(instance, filename):
    return datetime.now().strftime("%Y/%m/") + filename

class Category(models.Model):
    title = models.CharField(max_length=200)
    url_title = models.CharField(max_length=300)

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        super(Category, self).save()


class Posts(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(null=True, blank=True, upload_to=post_image)
    slug = models.SlugField(max_length=200, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    content = models.TextField()
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if self.slug is None or len(self.slug) < 2:
            self.slug = datetime.now().strftime("%Y/%m/") + slugify(self.title)
        super(Posts, self).save()
        if self.image:
            img = Image.open(self.image)
            img.save(self.image.path, quality=95)

client/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    phoneNumber = models.CharField(max_length=11)

product/models.py
from django.db import models

# Create your models here.

tag/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

# Create your views here.

blog/views/post_list.py
from django.shortcuts import render
from blog.models import *

def post_list(request):
    context = {}
    context['posts'] = Posts.objects.all()
    return render(request, 'blog/post_list.html', context)

client/views.py
from django.shortcuts import render

# Create your views here.

client/views/dasboard.py
from django.shortcuts import render

def dashboard(request):
    context = {}
    return render(request, 'client/dashboard.html')

client/views/signing.py
def signing(request):
    pass

client/views/sms.py
from django.shortcuts import render

def sendsms(request):
    context= {}
    if request.method == "POST" :
        context['req'] = {}
        context['req']['phoneNumber'] = request.POST.get('phoneNumber')
        context['req']['name'] = request.POST.get('name')
        context['req']['family'] = request.POST.get('family')
        context['req']['messageText'] = request.POST.get('messageText')
    return render(request, 'client/sms.html', context)

product/views.py
from django.shortcuts import render

# Create your views here.

tag/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>{% load static %}
<html class="loading" lang="en" data-textdirection="rtl">
<!-- BEGIN: Head-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <meta name="description"
          content="Frest admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
    <meta name="keywords"
          content="admin template, Frest admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="PIXINVENT">
    <title>{% block title %}{% endblock %}</title>
    <link rel="apple-touch-icon" href="{% static 'app-assets/images/ico/apple-icon-120.png' %}">
    <link rel="shortcut icon" type="image/x-icon" href="app-assets/images/ico/favicon.ico">
    <!-- BEGIN: Vendor CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/vendors-rtl.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/charts/apexcharts.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/extensions/dragula.min.css' %}">
    <!-- END: Vendor CSS-->

    <!-- BEGIN: Theme CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/bootstrap-extended.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/colors.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/components.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/themes/dark-layout.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/themes/semi-dark-layout.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/custom-rtl.min.css' %}">
    <!-- END: Theme CSS-->

    <!-- BEGIN: Page CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/core/menu/menu-types/vertical-menu.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/pages/widgets.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css-rtl/pages/dashboard-analytics.min.css' %}">
    <!-- END: Page CSS-->

    <!-- BEGIN: Custom CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/style-rtl.css' %}">
    <!-- END: Custom CSS-->
    {% block css %}{% endblock %}
</head>
<!-- END: Head-->
<!-- BEGIN: Body-->
<body{% block bodyclass %}{% endblock %}>
{% block body %}{% endblock %}
{% block js %}{% endblock %}
</body>
<!-- END: Body-->
</html>

templates/blog/post_list.html
{% extends "base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'app-assets/vendors/css/tables/datatable/dataTables.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'app-assets/vendors/css/tables/datatable/responsive.bootstrap4.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'app-assets/vendors/css/tables/datatable/buttons.bootstrap4.min.css' %}">
{% endblock %}
{% block title %}پست های آکادمی اول{% endblock %}
{% block bodyclass %} class="vertical-layout vertical-menu-modern boxicon-layout no-card-shadow 2-columns  navbar-sticky
    footer-static  " data-open="click" data-menu="vertical-menu-modern" data-col="2-columns"{% endblock %}
{% block body %}
    {% include "header.html" %}
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-12 mb-2 mt-1">
                    <div class="breadcrumbs-top">
                        <h5 class="content-header-title float-left pr-1 mb-0">DataTables</h5>
                        <div class="breadcrumb-wrapper d-none d-sm-block">
                            <ol class="breadcrumb p-0 mb-0 pl-1">
                                <li class="breadcrumb-item"><a href="index.html"><i class="bx bx-home-alt"></i></a>
                                </li>
                                <li class="breadcrumb-item active">Datatable
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body">
                <!-- Column selectors with Export Options and print table -->
                <section id="column-selectors">
                    <div class="row">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">
                                    {#          <h4 class="card-title">#}
                                    {#            Column selectors with Export and Print Options#}
                                    {#          </h4>#}
                                </div>
                                <div class="card-body card-dashboard">
                                    <div class="table-responsive">
                                        <table class="table table-striped dataex-html5-selectors">
                                            <thead>
                                            <tr>
                                                <th>عنوان پست</th>
                                                <th>دسته بندی</th>
                                                <th>نویسنده</th>
                                                <th>برچسب ها</th>
                                                <th>تاریخ انتشار</th>
                                                <th>کامنت ها</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for post in posts %}
                                            <tr>
                                                <td>{{ post.title }}</td>
                                                <td>{{ post.category }}</td>
                                                <td>{{ post.author.first_name }} {{ post.author.last_name }}</td>
                                                <td>--</td>
                                                <td>{% load jformat %}{{ post.created_at|jformat:"%Y/%m/%d" }}</td>
                                                <td>0</td>
                                            </tr>
                                            {% endfor %}
                                            </tbody>
                                            <tfoot>
                                            <tr>
                                                <th>عنوان پست</th>
                                                <th>دسته بندی</th>
                                                <th>نویسنده</th>
                                                <th>برچسب ها</th>
                                                <th>تاریخ انتشار</th>
                                                <th>کامنت ها</th>
                                            </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Column selectors with Export Options and print table -->
            </div>
        </div>
    </div>
    <!-- END: Content-->
    {% block js %}
        <script src="{% static 'app-assets/js/scripts/datatables/datatable.min.js' %}"></script>
        <script src="{% static 'app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'app-assets/vendors/js/tables/datatable/dataTables.bootstrap4.min.js' %}"></script>
        <script src="{% static 'app-assets/vendors/js/tables/datatable/dataTables.buttons.min.js' %}"></script>
        <script src="{% static 'app-assets/vendors/js/tables/datatable/buttons.html5.min.js' %}"></script>
        <script src="{% static 'app-assets/vendors/js/tables/datatable/buttons.print.min.js' %}"></script>
        <script src="{% static 'app-assets/vendors/js/tables/datatable/buttons.bootstrap4.min.js' %}"></script>
        <script src="{% static 'app-assets/vendors/js/tables/datatable/pdfmake.min.js' %}"></script>
        <script src="{% static 'app-assets/vendors/js/tables/datatable/vfs_fonts.js' %}"></script>
    {% endblock %}
    {% include "footer.html" %}
{% endblock %}

templates/client/sms.html
{% extends "base.html" %}
{% load static %}
{% block title %}پیامک ها{% endblock %}
{% block bodyclass %} class="vertical-layout vertical-menu-modern boxicon-layout no-card-shadow 2-columns  navbar-sticky
    footer-static" data-open="click" data-menu="vertical-menu-modern" data-col="2-columns"{% endblock %}
{% block body %}
    {% include "header.html" %}
    <div class="app-content content">
        <div class="content-overlay"></div>
        <div class="content-wrapper">
            <div class="content-header row">
                <div class="content-header-left col-12 mb-2 mt-1">
                    <div class="breadcrumbs-top">
                        <h5 class="content-header-title float-left pr-1 mb-0">ارسال پیامک</h5>
                        <div class="breadcrumb-wrapper d-none d-sm-block">
                            <ol class="breadcrumb p-0 mb-0 pl-1">
                                <li class="breadcrumb-item"><a href="{% url 'client:index' %}"><i class="bx bx-home-alt"></i></a>
                                </li>
                                <li class="breadcrumb-item active"><a href="#">ارسال پیامک</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-body"><!-- Basic Horizontal form layout section start -->
                <section id="basic-horizontal-layouts">
                    <div class="row match-height">
                        <div class="col-md-12 col-12">
                            <div class="card">
                                <div class="card-header">
                                    <h4 class="card-title">ارسال پیام</h4>
                                </div>
                                <div class="card-body">
                                    <form class="form form-horizontal" method="post">
                                        {% csrf_token %}
                                        <div class="form-body">
                                            <div class="row">
                                                <div class="col-md-2">
                                                    <label>شماره تلفن</label>
                                                </div>
                                                <div class="col-md-10 form-group ">
                                                    <div class="position-relative has-icon-left">
                                                        <input type="text" id="fname-icon" class="form-control"
                                                               name="phoneNumber"
                                                               placeholder="شماره همراه">
                                                        <div class="form-control-position">
                                                            <i class="bx bx-mobile"></i>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-2">
                                                    <label>نام</label>
                                                </div>
                                                <div class="col-md-10 form-group">
                                                    <div class="position-relative has-icon-left">
                                                        <input type="text" id="email-icon" class="form-control"
                                                               name="name" placeholder="نام">
                                                        <div class="form-control-position">
                                                            <i class="bx bx-user"></i>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-2">
                                                    <label>نام خانوادگی</label>
                                                </div>
                                                <div class="col-md-10 form-group">
                                                    <div class="position-relative has-icon-left">
                                                        <input type="text" id="contact-icon" class="form-control"
                                                               name="family"
                                                               placeholder="نام خانوادگی">
                                                        <div class="form-control-position">
                                                            <i class="bx bx-user"></i>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-md-2">
                                                    <label>پیامک</label>
                                                </div>
                                                <div class="col-md-10 form-group">
                                                    <div class="position-relative has-icon-left">
                                                        <input type="text" id="pass-icon" class="form-control"
                                                               name="messageText"
                                                               placeholder="متن پیامک">
                                                        <div class="form-control-position">
                                                            <i class="bx bx-lock"></i>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-12 d-flex justify-content-end ">
                                                    <button type="submit" class="btn btn-primary mr-1">ارسال پیامک</button>
                                                    <button type="reset" class="btn btn-light-secondary">انصراف</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- Basic Horizontal form layout section end -->
            </div>
        </div>
    </div>
    {% include "footer.html" %}
{% endblock %}

templates/footer.html
<!-- Buynow Button-->{% load static %}

<!-- demo chat-->
<div class="widget-chat-demo"><!-- widget chat demo footer button start -->
    <div class="buy-now"><a href="#" target="_blank" class="btn btn-danger">ارتباط با ما</a>

</div>
    <!-- widget chat demo footer button ends -->
    <!-- widget chat demo start -->
    <!--div class="widget-chat widget-chat-demo d-none">
        <div class="card mb-0">
            <div class="card-header border-bottom p-0">
                <div class="media m-75">
                    <a href="JavaScript:void(0);">
                        <div class="avatar mr-75">
                            <img src="{% static 'app-assets/images/portrait/small/avatar-s-2.jpg' %}" alt="avtar images" width="32"
                                 height="32">
                            <span class="avatar-status-online"></span>
                        </div>
                    </a>
                    <div class="media-body">
                        <h6 class="media-heading mb-0 pt-25"><a href="javaScript:void(0);">Kiara Cruiser</a></h6>
                        <span class="text-muted font-small-3">Active</span>
                    </div>
                </div>
                <div class="heading-elements">
                    <i class="bx bx-x widget-chat-close float-right my-auto cursor-pointer"></i>
                </div>
            </div>
            <div class="card-body widget-chat-container widget-chat-demo-scroll">
                <div class="chat-content">
                    <div class="badge badge-pill badge-light-secondary my-1">today</div>
                    <div class="chat">
                        <div class="chat-body">
                            <div class="chat-message">
                                <p>How can we help? 😄</p>
                                <span class="chat-time">7:45 AM</span>
                            </div>
                        </div>
                    </div>
                    <div class="chat chat-left">
                        <div class="chat-body">
                            <div class="chat-message">
                                <p>Hey John, I am looking for the best admin template.</p>
                                <p>Could you please help me to find it out? 🤔</p>
                                <span class="chat-time">7:50 AM</span>
                            </div>
                        </div>
                    </div>
                    <div class="chat">
                        <div class="chat-body">
                            <div class="chat-message">
                                <p>Stack admin is the responsive bootstrap 4 admin template.</p>
                                <span class="chat-time">8:01 AM</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer border-top p-1">
                <form class="d-flex" onsubmit="widgetChatMessageDemo();" action="javascript:void(0);">
                    <input type="text" class="form-control chat-message-demo mr-75" placeholder="Type here...">
                    <button type="submit" class="btn btn-primary glow px-1"><i class="bx bx-paper-plane"></i></button>
                </form>
            </div>
        </div>
    </div-->
    <!-- widget chat demo ends -->

</div>
<div class="sidenav-overlay"></div>
<div class="drag-target"></div>

<!-- BEGIN: Footer-->
<footer class="footer footer-static footer-light">
    <p class="clearfix mb-0"><span class="float-left d-inline-block">2021 آکادمی اول</span><span
            class="float-right d-sm-inline-block d-none">طراحی و توسعه توسط<i
            class="bx bxs-heart pink mx-50 font-small-3"></i><a class="text-uppercase"
                                                                  href="#"
                                                                  target="_blank">مرتضی داودی</a></span>
        <button class="btn btn-primary btn-icon scroll-top" type="button"><i class="bx bx-up-arrow-alt"></i></button>
    </p>
</footer>
<!-- END: Footer-->


<!-- BEGIN: Vendor JS-->

<script src="{% static 'app-assets/vendors/js/vendors.min.js' %}"></script>
<script src="{% static 'app-assets/fonts/LivIconsEvo/js/LivIconsEvo.tools.min.js' %}"></script>
<script src="{% static 'app-assets/fonts/LivIconsEvo/js/LivIconsEvo.defaults.min.js' %}"></script>
<script src="{% static 'app-assets/fonts/LivIconsEvo/js/LivIconsEvo.min.js' %}"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="{% static 'app-assets/vendors/js/charts/apexcharts.min.js' %}"></script>
<script src="{% static 'app-assets/vendors/js/extensions/dragula.min.js' %}"></script>
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="{% static 'app-assets/js/core/app-menu.min.js' %}"></script>
<script src="{% static 'app-assets/js/core/app.min.js' %}"></script>
<script src="{% static 'app-assets/js/scripts/components.min.js' %}"></script>
<script src="{% static 'app-assets/js/scripts/footer.min.js' %}"></script>
<script src="{% static 'app-assets/js/scripts/customizer.min.js' %}"></script>
<!-- END: Theme JS-->

<!-- BEGIN: Page JS-->
<script src="{% static 'app-assets/js/scripts/pages/dashboard-analytics.min.js' %}"></script>
<!-- END: Page JS-->

</body>
<!-- END: Body-->
</html>